### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ghost** [anim8js/anim8js#15]
Hello!

I see that you have set up a GitHub Pages site for this repository. Since KeyframeJS is on the anim8js repository, I am asking you to somehow fit KeyframeJS on the GitHub Pages site so I can get support for an amazing upcoming animation library like yours.

XtremePlayzCODE

**Comment by ClickerMonkey** [comment]
When your project is committed and ready I can place it on the repo website - but it should probably also have it's own site at `http://anim8js.github.io/keyframejs/` so you can show off your own work properly, documentation, etc.

**Comment by ghost** [comment]
True, I will do that sometime this month, I am very busy!

XtremePlayzCODE
